"""initial schema

Revision ID: 16ea46fbc113
Revises:
Create Date: 2026-09-22 23:02:29.338513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ea46fbc113'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Core account (Clash of Clans player) table ---
    op.create_table(
        'account__details',
        sa.Column('tag', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('exp_lvl', sa.Integer(), nullable=False),
        sa.Column('town_hall_lvl', sa.Integer(), nullable=False),
        sa.Column('trophies', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tag')
    )

    # --- App users (login accounts) ---
    # NOTE: no longer carries a `tag` column directly. A user can be linked
    # to zero, one, or many player tags via the `user_accounts` join table,
    # and the same player tag can be linked to many users.
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    # --- Many-to-many join: which users have which player tags linked ---
    op.create_table(
        'user_accounts',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('tag', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'tag'),
    )

    # --- Lookup table for display names of any type/id used below ---
    op.create_table(
        'id_to_name',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # --- Narrow ("EAV-style") tables, one row per item, matching the
    #     `buildings` / `traps` pattern ---

    op.create_table(
        'buildings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('building_type', sa.String(), nullable=False),
        sa.Column('building_lvl', sa.Integer(), nullable=False),
        sa.Column('building_cnt', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'traps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('trap_type', sa.String(), nullable=False),
        sa.Column('trap_lvl', sa.Integer(), nullable=False),
        sa.Column('trap_cnt', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'troops',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('troop_type', sa.String(), nullable=False),
        sa.Column('troop_lvl', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'spells',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('spell_type', sa.String(), nullable=False),
        sa.Column('spell_lvl', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'heroes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('hero_type', sa.String(), nullable=False),
        sa.Column('hero_lvl', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'hero_equipment',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('equipment_type', sa.String(), nullable=False),
        sa.Column('equipment_lvl', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'helpers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_tag', sa.String(), nullable=True),
        sa.Column('helper_type', sa.String(), nullable=False),
        sa.Column('helper_lvl', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # NOTE: `bbtroops` (Builder Base troops) has been intentionally removed.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helpers')
    op.drop_table('hero_equipment')
    op.drop_table('heroes')
    op.drop_table('spells')
    op.drop_table('troops')
    op.drop_table('traps')
    op.drop_table('buildings')
    op.drop_table('id_to_name')
    op.drop_table('user_accounts')
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table('account__details')
    # ### end Alembic commands ###