"""initial schema

Revision ID: 16ea46fbc113
Revises: 
Create Date: 2026-09-22 23:02:29.338513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ea46fbc113'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account__details',
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exp_lvl', sa.Integer(), nullable=False),
    sa.Column('town_hall_lvl', sa.Integer(), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("tag", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag"], ["account__details.tag"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table('id_to_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bbtroops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('raged_barbarian_lvl', sa.Integer(), nullable=False),
    sa.Column('sneaky_archer_lvl', sa.Integer(), nullable=False),
    sa.Column('beta_minion_lvl', sa.Integer(), nullable=False),
    sa.Column('boxer_giant_lvl', sa.Integer(), nullable=False),
    sa.Column('bomber_lvl', sa.Integer(), nullable=False),
    sa.Column('power_pekka_lvl', sa.Integer(), nullable=False),
    sa.Column('cannon_cart_lvl', sa.Integer(), nullable=False),
    sa.Column('drop_ship_lvl', sa.Integer(), nullable=False),
    sa.Column('baby_dragon_lvl', sa.Integer(), nullable=False),
    sa.Column('night_witch_lvl', sa.Integer(), nullable=False),
    sa.Column('hog_glider_lvl', sa.Integer(), nullable=False),
    sa.Column('electrofire_wizard_lvl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('building_type', sa.String(), nullable=False),
    sa.Column('building_lvl', sa.Integer(), nullable=False),
    sa.Column('building_cnt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helpers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('builders_Apprentice_lvl', sa.Integer(), nullable=False),
    sa.Column('lab_Assistant_lvl', sa.Integer(), nullable=False),
    sa.Column('prospector_lvl', sa.Integer(), nullable=False),
    sa.Column('alchemist_lvl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('barbarian_king_lvl', sa.Integer(), nullable=False),
    sa.Column('archer_queen_lvl', sa.Integer(), nullable=False),
    sa.Column('grand_warden_lvl', sa.Integer(), nullable=False),
    sa.Column('battle_machine_lvl', sa.Integer(), nullable=False),
    sa.Column('royal_champion_lvl', sa.Integer(), nullable=False),
    sa.Column('battle_copter_lvl', sa.Integer(), nullable=False),
    sa.Column('minion_prince_lvl', sa.Integer(), nullable=False),
    sa.Column('dragon_duke_lvl', sa.Integer(), nullable=False),
    sa.Column('giant_gauntlet_lvl', sa.Integer(), nullable=False),
    sa.Column('rocket_spear_lvl', sa.Integer(), nullable=False),
    sa.Column('spiky_ball_lvl', sa.Integer(), nullable=False),
    sa.Column('frozen_arrow_lvl', sa.Integer(), nullable=False),
    sa.Column('monolith_arrow_lvl', sa.Integer(), nullable=False),
    sa.Column('heroic_torch_lvl', sa.Integer(), nullable=False),
    sa.Column('fireball_lvl', sa.Integer(), nullable=False),
    sa.Column('snake_bracelet_lvl', sa.Integer(), nullable=False),
    sa.Column('dark_crown_lvl', sa.Integer(), nullable=False),
    sa.Column('magic_mirror_lvl', sa.Integer(), nullable=False),
    sa.Column('electro_boots_lvl', sa.Integer(), nullable=False),
    sa.Column('lavaloon_puppet_lvl', sa.Integer(), nullable=False),
    sa.Column('action_figure_lvl', sa.Integer(), nullable=False),
    sa.Column('meteor_staff_lvl', sa.Integer(), nullable=False),
    sa.Column('frost_flake_lvl', sa.Integer(), nullable=False),
    sa.Column('stick_horse_lvl', sa.Integer(), nullable=False),
    sa.Column('rocket_backpack_lvl', sa.Integer(), nullable=False),
    sa.Column('revenge_deck_lvl', sa.Integer(), nullable=False),
    sa.Column('barbarian_puppet_lvl', sa.Integer(), nullable=False),
    sa.Column('rage_vial_lvl', sa.Integer(), nullable=False),
    sa.Column('archer_puppet_lvl', sa.Integer(), nullable=False),
    sa.Column('invisibility_vial_lvl', sa.Integer(), nullable=False),
    sa.Column('eternal_tome_lvl', sa.Integer(), nullable=False),
    sa.Column('life_gem_lvl', sa.Integer(), nullable=False),
    sa.Column('seeking_shield_lvl', sa.Integer(), nullable=False),
    sa.Column('royal_gem_lvl', sa.Integer(), nullable=False),
    sa.Column('earthquake_boots_lvl', sa.Integer(), nullable=False),
    sa.Column('hog_rider_puppet_lvl', sa.Integer(), nullable=False),
    sa.Column('vampstache_lvl', sa.Integer(), nullable=False),
    sa.Column('haste_vial_lvl', sa.Integer(), nullable=False),
    sa.Column('giant_arrow_lvl', sa.Integer(), nullable=False),
    sa.Column('healer_puppet_lvl', sa.Integer(), nullable=False),
    sa.Column('rage_gem_lvl', sa.Integer(), nullable=False),
    sa.Column('healing_tome_lvl', sa.Integer(), nullable=False),
    sa.Column('henchmen_puppet_lvl', sa.Integer(), nullable=False),
    sa.Column('dark_orb_lvl', sa.Integer(), nullable=False),
    sa.Column('metal_pants_lvl', sa.Integer(), nullable=False),
    sa.Column('noble_iron_lvl', sa.Integer(), nullable=False),
    sa.Column('fire_heart_lvl', sa.Integer(), nullable=False),
    sa.Column('stun_blaster_lvl', sa.Integer(), nullable=False),
    sa.Column('flame_blower_lvl', sa.Integer(), nullable=False),
    sa.Column('electro_fangs_lvl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('lightning_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('healing_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('rage_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('jump_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('freeze_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('poison_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('earthquake_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('haste_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('clone_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('skeleton_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('bat_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('invisibility_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('recall_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('overgrowth_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('revive_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('ice_block_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('totem_spell_lvl', sa.Integer(), nullable=False),
    sa.Column('angry_spell_lvl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('trap_type', sa.String(), nullable=False),
    sa.Column('trap_lvl', sa.Integer(), nullable=False),
    sa.Column('trap_cnt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('troops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_tag', sa.String(), nullable=True),
    sa.Column('barbarian_lvl', sa.Integer(), nullable=False),
    sa.Column('archer_lvl', sa.Integer(), nullable=False),
    sa.Column('goblin_lvl', sa.Integer(), nullable=False),
    sa.Column('giant_lvl', sa.Integer(), nullable=False),
    sa.Column('wall_breaker_lvl', sa.Integer(), nullable=False),
    sa.Column('balloon_lvl', sa.Integer(), nullable=False),
    sa.Column('wizard_lvl', sa.Integer(), nullable=False),
    sa.Column('healer_lvl', sa.Integer(), nullable=False),
    sa.Column('dragon_lvl', sa.Integer(), nullable=False),
    sa.Column('pekka_lvl', sa.Integer(), nullable=False),
    sa.Column('minion_lvl', sa.Integer(), nullable=False),
    sa.Column('hog_rider_lvl', sa.Integer(), nullable=False),
    sa.Column('valkyrie_lvl', sa.Integer(), nullable=False),
    sa.Column('golem_lvl', sa.Integer(), nullable=False),
    sa.Column('witch_lvl', sa.Integer(), nullable=False),
    sa.Column('lava_hound_lvl', sa.Integer(), nullable=False),
    sa.Column('bowler_lvl', sa.Integer(), nullable=False),
    sa.Column('baby_dragon_lvl', sa.Integer(), nullable=False),
    sa.Column('miner_lvl', sa.Integer(), nullable=False),
    sa.Column('super_barbarian_lvl', sa.Integer(), nullable=False),
    sa.Column('super_archer_lvl', sa.Integer(), nullable=False),
    sa.Column('super_wall_breaker_lvl', sa.Integer(), nullable=False),
    sa.Column('super_giant_lvl', sa.Integer(), nullable=False),
    sa.Column('wall_wrecker_lvl', sa.Integer(), nullable=False),
    sa.Column('battle_blimp_lvl', sa.Integer(), nullable=False),
    sa.Column('yeti_lvl', sa.Integer(), nullable=False),
    sa.Column('sneaky_goblin_lvl', sa.Integer(), nullable=False),
    sa.Column('super_miner_lvl', sa.Integer(), nullable=False),
    sa.Column('rocket_balloon_lvl', sa.Integer(), nullable=False),
    sa.Column('ice_golem_lvl', sa.Integer(), nullable=False),
    sa.Column('electro_dragon_lvl', sa.Integer(), nullable=False),
    sa.Column('stone_slammer_lvl', sa.Integer(), nullable=False),
    sa.Column('inferno_dragon_lvl', sa.Integer(), nullable=False),
    sa.Column('super_valkyrie_lvl', sa.Integer(), nullable=False),
    sa.Column('dragon_rider_lvl', sa.Integer(), nullable=False),
    sa.Column('super_witch_lvl', sa.Integer(), nullable=False),
    sa.Column('siege_barracks_lvl', sa.Integer(), nullable=False),
    sa.Column('ice_hound_lvl', sa.Integer(), nullable=False),
    sa.Column('super_bowler_lvl', sa.Integer(), nullable=False),
    sa.Column('super_dragon_lvl', sa.Integer(), nullable=False),
    sa.Column('headhunter_lvl', sa.Integer(), nullable=False),
    sa.Column('super_wizard_lvl', sa.Integer(), nullable=False),
    sa.Column('super_minion_lvl', sa.Integer(), nullable=False),
    sa.Column('log_launcher_lvl', sa.Integer(), nullable=False),
    sa.Column('flame_flinger_lvl', sa.Integer(), nullable=False),
    sa.Column('battle_drill_lvl', sa.Integer(), nullable=False),
    sa.Column('electro_titan_lvl', sa.Integer(), nullable=False),
    sa.Column('apprentice_warden_lvl', sa.Integer(), nullable=False),
    sa.Column('super_hog_rider_lvl', sa.Integer(), nullable=False),
    sa.Column('ruin_witch_lvl', sa.Integer(), nullable=False),
    sa.Column('root_rider_lvl', sa.Integer(), nullable=False),
    sa.Column('druid_lvl', sa.Integer(), nullable=False),
    sa.Column('thrower_lvl', sa.Integer(), nullable=False),
    sa.Column('troop_launcher_lvl', sa.Integer(), nullable=False),
    sa.Column('super_yeti_lvl', sa.Integer(), nullable=False),
    sa.Column('furnace_lvl', sa.Integer(), nullable=False),
    sa.Column('meteor_golem_lvl', sa.Integer(), nullable=False),
    sa.Column('sky_wagon_lvl', sa.Integer(), nullable=False),
    sa.Column('lassi_lvl', sa.Integer(), nullable=False),
    sa.Column('mighty_yak_lvl', sa.Integer(), nullable=False),
    sa.Column('electro_owl_lvl', sa.Integer(), nullable=False),
    sa.Column('unicorn_lvl', sa.Integer(), nullable=False),
    sa.Column('phoenix_lvl', sa.Integer(), nullable=False),
    sa.Column('poison_lizard_lvl', sa.Integer(), nullable=False),
    sa.Column('diggy_lvl', sa.Integer(), nullable=False),
    sa.Column('frosty_lvl', sa.Integer(), nullable=False),
    sa.Column('spirit_fox_lvl', sa.Integer(), nullable=False),
    sa.Column('angry_jelly_lvl', sa.Integer(), nullable=False),
    sa.Column('sneezy_lvl', sa.Integer(), nullable=False),
    sa.Column('greedy_raven_lvl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['account__details.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table('troops')
    op.drop_table('traps')
    op.drop_table('spells')
    op.drop_table('heroes')
    op.drop_table('helpers')
    op.drop_table('buildings')
    op.drop_table('bbtroops')
    op.drop_table('id_to_name')
    op.drop_table('account__details')
    # ### end Alembic commands ###
